music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [ :index, :new, :create ]
  resource :session #singular, generates routes for new_session, edit_session, show_session
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

end 

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :email, uniqueness: true
    after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom.urlsafe_base64(16)             
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if user.nil? || !user.is_password?(password)
        user
    end 

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end 
    
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        bcrypt_password = BCrypt::Password.new(self.password_digest)
        bcrypt_password.is_password?(password)
    end

    private
    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end
end 

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in? #the ones views will need

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token]) #optimized to not query db again if current_user exists
        #user = User.find_by(session_token: session[:session_token])
    end 

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end 

    def logged_in?
        !!current_user
    end 

    def log_in_user!(user)
        session[:session_token] = user.reset_session_token! #reset so it's a new one, NOT the one from when they were not logged in
    end 

    def logout!(user)
        user.reset_session_token!
        session[:session_token] = nil
    end 
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index 
        @bands = Band.all
        render :index
    end

    def new 
        @band = Band.new 
        render :new   
    end 

    def create 
        @band = Band.new(band_params)

        if @band.save
            redirect_to bands_url
        else  
            redirect_to new_band_url
        end 
    end 

    def edit
        @band = Band.find_by(id: params[:id])
        render :edit 
    end 

    def update
        @band = Band.find_by(id: params[:id])

        if @band.update_attributes(band_params)
            redirect_to bands_url
        else  
            redirect_to edit_band_url
        end 
    end 

    def show 
        @band = Band.find_by(id: params[:id])

        if @band 
            render :show
        else  
            redirect_to bands_url
        end 
    end 

    def destroy 
        @band = Band.find_by(id: params[:id])

        @band.delete if @band
        redirect_to bands_url
    end 

    private
    def band_params
        params.require(:band).permit(:name)
    end 
end 

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :ensure_logged_in, only: [ :destroy ]

    def new
        render :new #new session is the log-in
    end 

    def create 
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        
        if user 
            log_in_user!(user) #THIS IS LOGGINING IN WHEN SOMEONE PRESSES THE NEW_SESSION_URL (log in on main page for pre-existing user who is currently logged out)
            redirect_to user_url(user)
        else  
            redirect_to new_user_url #invalid login credentials, try again
        end
    end 

    def destroy
        logout!(current_user) #rails assumes need to render template w same name as action when no redirect or render explicitly stated
        redirect_to new_session_url
    end 
end 



#sessions and user controllers do not communicate with each other

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        render :show
    end 

    def new 
        #debugger
        @user = User.new
        render :new 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save
            log_in_user!(@user) #THIS IS LOGGING IN AFTER SIGNING UP
            redirect_to user_url(@user) #for now just redirect here
        else  
            redirect_to new_user_url #invalid singup credentials, try again
        end 
    end 

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/bands/edit.html.erb
<h1>edit your band!</h1>

<form action="<%= band_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <label for="band_name">band name:
        <input type="text" name="band[name]" value="<%= @band.name %>">
    </label>

    <input type="submit" value="submit">
</form>

music_app/app/views/bands/index.html.erb
<h2>welcome to the bands page! take a gander</h2>
<% @bands.each do |band| %>
    <%= band.name %>
    <br />
<% end %>

music_app/app/views/bands/new.html.erb
<h1>add a band!</h1>

<form action="/bands" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="band_name">band name:
        <input type="text" id="band_name" name="band[name]" value="">
    </label>

    <input type="submit" value="submit">
</form>

music_app/app/views/bands/show.html.erb
<h1>here is your chosen band!</h1>

<%= @band.name %>

<br />

<form action="<% band_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">

    <input type="submit" value="delete">
</form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>~* music app*~</title>
    <header>~* music app*~
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% #debugger %>
    <div>
    <% if logged_in? %>
      <form action="/session" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log out">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">sign up!</a>
      <a href="<%= new_session_url %>">log in!</a>
    <% end %>
    </div>
    </header>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<p> create your account! </p>
<form action="<%= users_url %>", method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="user_email">email:
        <input type="text" id="user_email" name="user[email]" value="">
    </label>

    <br />

    <label for="user_password">password:
        <input type="text" id="user_passwod" name="user[password]" value="">
    </label>

    <br />

    <input type="submit" value="sign up!"/>
</form>

music_app/app/views/users/show.html.erb
<h2><%= current_user.nil? ? "you're not logged in!" : current_user.email %></h2>